### ISSUE TITLE
Member Fee Tracking

### ISSUE THREAD

**Issue by phatgg221** [rmit-nct/hub#15]
Implement a member fee tracking system allowing finance members to track who has paid and who hasn't. Includes a sortable table for paid and unpaid members. Finance members can update the payment status. Upon approval, the paid amount is added to the total wallet.

TASK: 

- [x] Front-end design for member fee tracking table
- [ ] Implement basic functionalities of the tracking table
- [ ] Enable finance members to change member fee payment status
- [ ] Automatic addition of paid amount to the total wallet
