### ISSUE TITLE
Bill Tracking

### ISSUE THREAD

**Issue by phatgg221** [rmit-nct/hub#16]
Create a feature for tracking bills from shops. Finance department can assign responsible persons and receive reminders every three days to collect red and white bills. Includes functionality to associate specific events to specific members and notify them to collect bills.

- [x] Front-end design for bill tracking feature
- [ ] Implement creation of bills and assignment of responsible persons
- [ ] Create event form with details including assigned person for bill collection
- [ ] Implement notification system to remind assigned members to collect bills
